apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # TODO: changeme
  name: workshop-directus-bank
  namespace: argocd
spec:
  destination:
    # TODO: changeme
    namespace: workshop-bank
    server: https://kubernetes.default.svc
  project: workshop-bank
  sources:
    - helm:
        valueFiles:
          - values.yaml
          - values-example.yaml
      path: projects/directus/chart
      repoURL: https://github.com/Peelz/fatboy-wanna-fly.git
    - helm:
        valueFiles:
          - values.yaml
          - values-example.yaml
      path: projects/directus/chart-directus
      repoURL: https://github.com/Peelz/fatboy-wanna-fly.git
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
