#!/bin/ash

SQL_OUT_FILE=$(pwd)/sql/grant.sql

cat <<EOF > "$SQL_OUT_FILE"
  GRANT CONNECT ON DATABASE $DB_NAME TO $DB_DIRECTUS_USER;
  GRANT USAGE ON SCHEMA public TO $DB_DIRECTUS_USER;
  GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO $DB_DIRECTUS_USER;
EOF

run-pgsql-script-as-postgres.sh "$SQL_OUT_FILE"
rm "$SQL_OUT_FILE"
