GRANT USAGE ON SCHEMA asset TO directus;
GRANT USAGE ON SCHEMA directus TO directus;
GRANT USAGE ON SCHEMA main TO directus;

GRANT CREATE ON SCHEMA asset TO directus;
GRANT CREATE ON SCHEMA directus TO directus;
GRANT CREATE ON SCHEMA main TO directus;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA directus TO directus;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA asset TO directus;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA main TO directus;

ALTER DEFAULT PRIVILEGES FOR ROLE de_viper_admin IN SCHEMA directus GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON TABLES TO directus;
ALTER DEFAULT PRIVILEGES FOR ROLE de_viper_admin IN SCHEMA asset GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON TABLES TO directus;
ALTER DEFAULT PRIVILEGES FOR ROLE de_viper_admin IN SCHEMA main GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON TABLES TO directus;
