
image:
  tag: 10.12

extraEnvVars:
  - name: DB_CLIENT
    value: "pg"
  - name: DB_HOST
    value: "postgresql-viper.database.svc.cluster.local"
  - name: DB_PORT
    value: "5432"
  # TODO: changeme
  - name: DB_DATABASE
    value: "workshop_{changeme}"
  - name: DB_SEARCH_PATear
    value: "array:directus,asset"
  # TODO: changeme
  - name: DB_USER
    value: workshop_{changeme}
  # TODO: changeme
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: workshop-{changeme}-psql-user-directus
        key: DB_DIRECTUS_USER_PASS
  - name: KEY
    valueFrom:
      secretKeyRef:
        name: directus-secrets-env
        key: KEY
  - name: SECRET
    valueFrom:
      secretKeyRef:
        name: directus-secrets-env
        key: SECRET
  - name: ADMIN_PASSWORD
    valueFrom:
      secretKeyRef:
        name: directus-secrets-env
        key: ADMIN_PASSWORD
  - name: ADMIN_EMAIL
  # TODO: changeme
    value: 'sa@mordee.com'

redis:
  enabled: false

nodeSelector:
  cloud.google.com/gke-spot: "true"

tolerations:
  - key: continuity
    operator: Equal
    value: preemptible
    effect: NoExecute

virtualService:
  domainName:
    # TODO: changeme
    - '{changeme}-directus.pluto.tdh.bluewhale.space'

