apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # TODO: changeme
  name: workshop-directus-{changeme}-eco
  namespace: argocd
spec:
  destination:
    # TODO: changeme
    namespace: workshop-{changeme}
    server: https://kubernetes.default.svc
  project: workshop-{changeme}
  source:
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml
    path: projects/directus/chart
    repoURL: {gitrepo}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # TODO: changeme
  name: workshop-directus-{changeme}
  namespace: argocd
spec:
  destination:
    # TODO: changeme
    namespace: workshop-{changeme}
    server: https://kubernetes.default.svc
  project: workshop-{changeme}
  source:
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml
    path: projects/directus/chart-directus
    repoURL: {gitrepo}
