apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # TODO: changeme
  name: workshop-directus-{changeme}-ecosys
  namespace: argocd
spec:
  destination:
    namespace: {changeme}
    server: https://kubernetes.default.svc
  project: database
  source:
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml
    path: projects/directus/chart
    repoURL: {git repo url}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
 
