apiVersion: v2
appVersion: v0.1.0
description: Directus Ecosystem Chart
keywords:
  - directus 
kubeVersion: ">= 1.19.0-0"
maintainers:
  - email: anucha.mai@truedigital.com
    name: Anucha Mai.
name: biz-directus-ecosystem
version: 0.1.0

