gcpProjectId: tdg-dh-truehealth-core-nonprod
clusterLocation: asia-southeast1
clusterName: tdh-dev-octopus

serviceAccount:
  # TODO: changeme
  secretStore: workshop-eso-bank
  # TODO: changeme
  directus: workshop-bank

namespace: workshop-bank

database:
  postgres:
    host: postgresql-viper.database.svc.cluster.local
    # TODO: change me 
    dbName: "workshop_bank"
    users:
      postgres:
        gcpSecretRef: "pg-viper-admin-password"
        kubeSecretRef: "db-psql-user-postgres"
      directus:
        version: 1
        userName: "workshop_bank"
        gcpSecretRef: "workshop-bank-psql-user-db-directus"
        kubeSecretRef: "workshop-bank-psql-user-directus"

argocd:
  valueFiles:
    - values.yaml
    - values-dev.yaml

directus:
  secretRefs:
    key: 'workshop-bank-directus-mordee-key'
    secret: 'workshop-bank-directus-mordee-secret'
    admin: 'workshop-bank-directus-admin-password'
