gcpProjectId: tdg-dh-truehealth-core-nonprod
clusterLocation: asia-southeast1
clusterName: tdh-dev-octopus

serviceAccount:
  # TODO: changeme
  secretStore: workshop-eso-{changeme}
  # TODO: changeme
  directus: workshop-{changeme}

namespace: workshop-{changeme}

database:
  postgres:
    host: postgresql-viper.database.svc.cluster.local
    # TODO: change me 
    dbName: "workshop_{changeme}"
    users:
      postgres:
        gcpSecretRef: "pg-viper-admin-password"
        kubeSecretRef: "db-psql-user-postgres"
      directus:
        version: 1
        userName: "workshop_{changeme}"
        gcpSecretRef: "workshop-{changeme}-psql-user-db-directus"
        kubeSecretRef: "workshop-{changeme}-psql-user-directus"
argocd:
  valueFiles:
    - values.yaml
    - values-dev.yaml

dbJob:
  # TODO: changeme
  repo: https://github.com/Peelz/fatboy-wanna-fly.git
