apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.directus }}
  namespace: {{ .Release.Namespace }}
  annotations:
    iam.gke.io/gcp-service-account: {{.Values.serviceAccount.directus}}@{{.Values.gcpProjectId}}.iam.gserviceaccount.com
