apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.dory }}
  namespace: {{ .Release.Namespace }}
  annotations:
    iam.gke.io/gcp-service-account: {{.Values.serviceAccount.dory}}@{{.Values.gcpProjectId}}.iam.gserviceaccount.com
