apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: directus-secrets-env
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: {{ .Values.serviceAccount.secretStore }}
  target:
    name: directus-secrets-env
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DB_PASSWORD: {{ print "\"{{ .dbPassword }}\"" }}
        KEY: {{ print "\"{{ .key }}\"" }}
        SECRET: {{ print "\"{{ .secret }}\"" }}
        ADMIN_PASSWORD: {{ print "\"{{ .adminPassword }}\"" }}
  data:
    - secretKey: dbPassword # Password for connecting to postgres
      remoteRef:
        key: {{ .Values.postgres.users.directus.gcpSecretRef }}
    - secretKey: key # Key env for directus instance
      remoteRef:
        key: {{ .Values.directus.secretRefs.key }}
    - secretKey: secret # Secret env for directus instance
      remoteRef:
        key: {{ .Values.directus.secretRefs.secret }}
    - secretKey: adminPassword # Initial directus admin password
      remoteRef:
        key: {{ .Values.directus.secretRefs.admin }}
