apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.database.postgres.users.directus.kubeSecretRef }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 8760h
  secretStoreRef:
    kind: SecretStore
    name: {{ .Release.Namespace }}-secret-store
  target:
    name: {{ .Values.database.postgres.users.directus.kubeSecretRef }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.database.postgres.users.directus.gcpSecretRef }}

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.database.postgres.users.postgres.gcpSecretRef }}
spec:
  refreshInterval: 8760h
  secretStoreRef:
    kind: SecretStore
    name: {{ .Release.Namespace }}-secret-store
  target:
    name: {{ .Values.database.postgres.users.postgres.kubeSecretRef }}
    creationPolicy: Owner
    template:
      data:
        POSTGRES_USER_PASS: {{`"{{.admin_password}}"`}}
  data:
    - secretKey: admin_password
      remoteRef:
        key: {{ .Values.database.postgres.users.postgres.gcpSecretRef }}
