apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Release.Namespace }}-secret-store
  namespace: {{ .Values.namespace }}
spec:
  provider:
    gcpsm:
      projectID: {{ .Values.gcpProjectId }}
      auth:
        workloadIdentity:
          clusterLocation: {{ .Values.clusterLocation }}
          clusterName: {{ .Values.clusterName }}
          clusterProjectID: {{ .Values.gcpProjectId }}
          serviceAccountRef:
            name: {{ .Values.serviceAccount.secretStore }}
            namespace: {{ .Values.namespace }}
