apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.secretStore }}
  namespace: {{ .Values.namespace }}
  labels:
    operator: eso
  annotations:
    iam.gke.io/gcp-service-account: {{.Values.serviceAccount.secretStore}}@{{.Values.gcpProjectId}}.iam.gserviceaccount.com
